USE db;

START TRANSACTION;

DROP TABLE IF EXISTS token;

CREATE TABLE token (
        id INT UNSIGNED AUTO_INCREMENT UNIQUE PRIMARY KEY,
        value BINARY(12) NOT NULL DEFAULT(RANDOM_BYTES(12)),
        album VARCHAR(255) NOT NULL,
        usages INT UNSIGNED NOT NULL DEFAULT(1),
        created DATETIME(4) NOT NULL DEFAULT(NOW(4))
);

COMMIT;
